# Generated by Django 6.0.5 on 2026-05-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
