# Generated by Django 6.0.5 on 2026-05-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_xpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xpost',
        ),
    ]
