# Generated by Django 6.0.5 on 2026-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(choices=[('sp', 'SP'), ('mu', 'MU'), ('mo', 'MO'), ('te', 'TEL'), ('other', 'OTHER')], default='sp', max_length=5),
        ),
    ]
