# Generated by Django 6.0.5 on 2026-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/avatar.png', upload_to='profile_pictures/'),
        ),
    ]
