"""
Django settings for facebook project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import datetime
from datetime import timezone
from django.utils.translation import gettext_lazy as _
from django.utils import timezone as tz
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rfs-uoe-=jq7^!i*z%rf$(mnat!m@haxy&5@&h8wfy(m=ot7_!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'accounts.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'common.apps.CommonConfig',
    'django_tables2',
    'crispy_forms',
    "crispy_bootstrap5",
    'django.contrib.humanize',
    'django_jalali',
    'chartjs',
    'slick_reporting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'facebook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facebook.wsgi.application'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# SLICK_REPORTING_SETTINGS = {
#
#     "JQUERY_URL": "https://code.jquery.com/jquery-3.7.0.min.js",
#
#     "DEFAULT_START_DATE_TIME": datetime(
#         tz.now().year,
#         1,
#         1,
#         0,
#         0,
#         0,
#         tzinfo=timezone.utc
#     ),
#
#     "DEFAULT_END_DATE_TIME": tz.now(),
#     "DEFAULT_CHARTS_ENGINE": 'chartsjs',
#
#     "MEDIA": {
#
#         "override": False,
#
#         "js": (
#
#             "https://cdn.jsdelivr.net/momentjs/latest/moment.min.js",
#
#             "https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js",
#
#             "https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js",
#
#             "slick_reporting/slick_reporting.js",
#
#             "slick_reporting/slick_reporting.report_loader.js",
#
#             "slick_reporting/slick_reporting.datatable.js",
#         ),
#
#         "css": {
#
#             "all": (
#
#                 "https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css",
#
#             ),
#         },
#     },
#
#     "FONT_AWESOME": {
#
#         "CSS_URL": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css",
#
#         "ICONS": {
#
#             "pie": "fas fa-chart-pie",
#
#             "bar": "fas fa-chart-bar",
#
#             "line": "fas fa-chart-line",
#
#             "area": "fas fa-chart-area",
#
#             "column": "fas fa-cahrt-bar",
#         },
#     },

#     "CHARTS": {
#
#         "highcharts": "$.slick_reporting.highcharts.displayChart",
#
#         "chartjs": "$.slick_reporting.chartjs.displayChart",
#     },
#
# "MESSAGES": {
#     "total": "Total",
#     "export_to_csv": "Export CSV",
#     "print_report": "Print Report",
# },
# }
SLICK_REPORTING_SETTINGS = {
    "JQUERY_URL": "https://code.jquery.com/jquery-3.7.0.min.js",
}
